// AUTO-GENERATED by scripts/gen-references.mjs — do not edit by hand.
export const REFERENCE_IMAGES: string[] = [
  "/references/ref-16.jpeg",
  "/references/ref-13.jpeg",
  "/references/ref-6.jpg",
  "/references/ref-7.jpg",
  "/references/ref-14.jpeg",
  "/references/ref-12.jpeg",
  "/references/ref-1.jpg",
  "/references/ref-17.jpeg",
  "/references/ref-11.jpeg",
  "/references/ref-5.jfif",
  "/references/ref-8.png",
  "/references/ref-9.jpg",
  "/references/ref-10.jpg",
  "/references/ref-4.png",
  "/references/ref-3.webp",
  "/references/ref-18.jpeg",
  "/references/ref-2.jpg",
  "/references/ref-15.jpeg"
];
